[package]
edition = "2018"
name = "ultimate-ultimate-ttt"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
crossterm = "0.21.0"
flume = "0.10.9"
jsonl = "4.0"
serde = {version = "1.0", features = ["derive"]}
